SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 20
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5

PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_LIVES = 3
PLAYER_INVULNERABILITY_TIME = 2
PLAYER_ACCELERATION = 200
PLAYER_FRICTION = 0.98

SCORE_ASTEROID_LARGE = 20
SCORE_ASTEROID_MEDIUM = 50
SCORE_ASTEROID_SMALL = 100

POWERUP_DURATION = 10
POWERUP_SPAWN_CHANCE = 0.1
